FROM nginx:stable-alpine3.17-slim
ARG COMPOSE_COLOR

RUN rm -rf /etc/nginx/conf.d/default.conf
RUN echo "nginx image will be generated for : $COMPOSE_COLOR"
COPY nginx.conf /etc/nginx/nginx.conf
COPY nginx.$COMPOSE_COLOR.conf /etc/nginx/conf.d/nginx.backend.conf
VOLUME ["/data", "/etc/nginx", "/var/log/nginx"]
WORKDIR /etc/nginx
CMD ["nginx"]
EXPOSE 80